import { COUNTRY_CODES, normalizeCountryCode } from './country-regions.js';

export const COUNTRY_NAME_POLICY_VERSION = 1;

/** Static English display names, ordered exactly like the supported country registry. */
export const COUNTRY_NAMES_BY_CODE = Object.freeze({
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua & Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia & Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "St. Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Côte d’Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard & McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "St. Kitts & Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "St. Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "St. Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar (Burma)",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "St. Pierre & Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé & Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks & Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad & Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "St. Vincent & Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis & Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
});

/** Deliberate, unambiguous English alternatives to the canonical short names. */
export const COUNTRY_NAME_ALIASES = Object.freeze({
  'United States of America': 'US',
  USA: 'US',
  'Great Britain': 'GB',
  Britain: 'GB',
  'Republic of Korea': 'KR',
  'Korea, Republic of': 'KR',
  'Democratic People’s Republic of Korea': 'KP',
  'Korea, Democratic People’s Republic of': 'KP',
  'Russian Federation': 'RU',
  Turkey: 'TR',
  'Viet Nam': 'VN',
  'Iran, Islamic Republic of': 'IR',
  'Syrian Arab Republic': 'SY',
  'Bolivia, Plurinational State of': 'BO',
  'Venezuela, Bolivarian Republic of': 'VE',
  'Tanzania, United Republic of': 'TZ',
  'Moldova, Republic of': 'MD',
  'Lao People’s Democratic Republic': 'LA',
  'Brunei Darussalam': 'BN',
  'Czech Republic': 'CZ',
  'Ivory Coast': 'CI',
  "Cote d'Ivoire": 'CI',
  "Côte d'Ivoire": 'CI',
  'Cape Verde': 'CV',
  Swaziland: 'SZ',
  'East Timor': 'TL',
  'State of Palestine': 'PS',
  'Palestinian Territories': 'PS',
  'Taiwan, Province of China': 'TW',
  'Hong Kong SAR China': 'HK',
  Macau: 'MO',
  'Macao SAR China': 'MO',
  'The Bahamas': 'BS',
  'The Gambia': 'GM',
  'Federated States of Micronesia': 'FM',
  'Congo-Kinshasa': 'CD',
  'DR Congo': 'CD',
  'Congo-Brazzaville': 'CG',
  'Saint Barthélemy': 'BL',
  'St. Barthélemy': 'BL',
  'Saint Martin (French part)': 'MF',
  'Sint Maarten (Dutch part)': 'SX',
  'United States Virgin Islands': 'VI',
  'Holy See': 'VA',
  'Cocos Islands': 'CC',
});

const apostrophes = /[‘’‛]/gu;
const dashes = /[‐‑‒–—―−]/gu;

export function normalizeCountryName(value) {
  if (typeof value !== 'string') throw new TypeError('country name must be a string');
  return value.normalize('NFKC').trim().replace(/\s+/gu, ' ')
    .replace(apostrophes, '’').replace(dashes, '-').toLowerCase();
}

const countryCodesByNormalizedName = new Map();
function registerName(name, code) {
  const normalized = normalizeCountryName(name);
  const existing = countryCodesByNormalizedName.get(normalized);
  if (existing !== undefined && existing !== code) {
    throw new TypeError(`Conflicting country name: ${name}`);
  }
  countryCodesByNormalizedName.set(normalized, code);
}
for (const code of COUNTRY_CODES) registerName(COUNTRY_NAMES_BY_CODE[code], code);
for (const [name, code] of Object.entries(COUNTRY_NAME_ALIASES)) registerName(name, code);

export function getCountryName(countryCode) {
  return COUNTRY_NAMES_BY_CODE[normalizeCountryCode(countryCode)];
}

export function getCountryCodeByName(countryName) {
  const normalized = normalizeCountryName(countryName);
  if (normalized === '') return null;
  return countryCodesByNormalizedName.get(normalized) ?? null;
}
